
cmd = @printf "%-8s %s\n" $1 $2

# Tool names
CP		= @cp -p
ECHO	= echo

MKDIR		= @mkdir -p $1

# limited to 5 entries as no way to get all args
REMOVE		= $(call cmd,"RM","$1");set +e;rm -rf $1

PRINTF	= printf

# Used to separate commands in foreach.
# NOTE this MUST have 2 empty lines between define and endef for it to work!
define \n


endef
